server:
  port: 8803
spring:
  application:
    name: cloud-stream-consumer

  cloud:
    stream:
      binders:
        rabbit:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: localhost
                port: 5672
                username: dev
                password: dev
      bindings:
        input:
          destination: studyExchange
          content-type: application/json
          binder: rabbit
          group: msA
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    lease-renewal-interval-in-seconds: 2
    lease-expiration-duration-in-seconds: 5
    instance-id: receive-8803.com
    prefer-ip-address: true
